sudo: false
services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker ps -a | grep mariadb
  - docker ps -a | grep _danillonunes
  - docker ps -a | grep _php
  - docker ps -a | grep _nginx
