danillonunes:
  build: .
  environment:
    DB_HOST: mariadb
    DB_NAME: danillonunes
    DB_USER: danillonunes
    DB_PASSWORD: danillonunes

nginx:
  build: docker/nginx
  ports:
    - "80"
  links:
    - php
  volumes_from:
    - danillonunes
  environment:
    PHP_CGI_1: danillonunes_php:9000

mariadb:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
    MYSQL_USER: danillonunes
    MYSQL_PASS: danillonunes
    MYSQL_DATABASE: danillonunes
    MYSQL_ROOT_PASSWORD: danillonunes

php:
  build: docker/php
  ports:
    - "9000:9000"
  volumes_from:
    - danillonunes
  links:
    - mariadb
