<?php

/**
 * Implements hook_init().
 *
 * Insert Reinvigorate's javascript code into page.
 */
function reinvigorate_init() {
  $track_code = variable_get('reinvigorate_account', FALSE);

  if ($track_code) {
    drupal_add_js('http://include.reinvigorate.net/re_.js',
      array('type' => 'external', 'scope' => 'footer')
    );
    drupal_add_js("try { reinvigorate.track('$track_code'); } catch(err) {}",
      array('type' => 'inline', 'scope' => 'footer')
    );
  }
}

/**
 * Implements hook_menu().
 */
function reinvigorate_menu() {
  $items['admin/config/services/reinvigorate'] = array(
    'title' => 'Reinvigorate',
    'description' => 'Configure Reinvigorate track code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reinvigorate_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Configure Reinvigorate track code.
 */
function reinvigorate_settings() {
  $form['reinvigorate_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Reinvigorate track code'),
    '#default_value' => variable_get('reinvigorate_account', ''),
  );

  return system_settings_form($form);
}
